function resizedImage = CNNresize(rgbImage)
%Image Processing Function
%
% rgbImage - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------
resizedImage = imresize(rgbImage, [252, 252]);

global m
baseFileName = num2str(m);
m = m+1;
fname = strcat('image-', baseFileName,'.jpg');
imwrite(resizedImage, fname, 'jpg');
%--------------------------------------------------------------------------