function filteredImage = filterHP(rgbImage)
%Image Processing Function
%
% rgbImage - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------

grayImage = rgb2gray(rgbImage);

% Get the dimensions of the image.  numberOfColorBands should be = 1.
[rows columns numberOfColorBands] = size(grayImage);

% HP filtering
% 5x5
kernel_1 = [-1 2 -2 2 -1; 2 -6 8 -6 2; -2 8 -18 8 -2; 2 -6 8 -6 2; -1 2 -2 2 -1] / 12; %tuama kernel.
kernel_2 = [0 -1 -1 -1 0; -1 2 -4 2 -1; -1 -4 13 -4 -1; -1 2 -4 2 -1; 0 -1 -1 -1 0];
% 3x3
kernel_3 = [-1 -2 -1; -2 12 -2; -1 -2 -1]/16;
kernel_4 = [-1 -1 -1; -1 9 -1; -1 -1 -1];

% Filter the image.  Need to cast to single so it can be floating point
% which allows the image to have negative values.
filteredImage = imfilter(single(grayImage), kernel_3);

global m
baseFileName = num2str(m);
m = m+1;
fname = strcat('image-', baseFileName,'--','.jpg');
imwrite(filteredImage, fname, 'jpg');
%--------------------------------------------------------------------------